
const StatusFilled          = "FILL"
const StatusError           = "ERROR"
const StatusPartiallyFilled = "PARTIAL_FILL"
const StatusOpen            = "OPEN"
const StatusCancelled       = "CANCEL"
const StatusComplete        = "COMPLETE"
const StatusExpired         = "EXPIRED"

const SideBuy  = "BUY"
const SideSell = "SELL"

const CoinbasePro = "GDAX"
const Gemini      = "GEMINI"
const Binance     = "BINANCE"
const Bittrex     = "BITTREX"
const Kraken      = "KRAKEN"
const Bitfinex    = "BITFINEX"
const Poloniex    = "POLONIEX"

const Usd = "usd"
const Eur = "eur"
const Gbp = "gbp"

const Usdt = "usdt"
const Usdc = "usdc"
const Tusd = "tusd"
const Gusd = "gusd"
const Dai  = "dai"
const Pax  = "pax"

const Btc = "btc"
const Bch = "bch"
const Eth = "eth"
const Ltc = "ltc"
const Xrp = "xrp"
const Xlm = "xlm"
const Zrx = "zrx"
